In [1]:
from src.models.Encodec import Encodec
encodec = Encodec()


/homes/jpmg86/anaconda3/envs/MuMRVQ/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/homes/jpmg86/anaconda3/envs/MuMRVQ/lib/python3.9/site-packages/torch/nn/utils/weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")


In [2]:
from audiocraft.modules.codebooks_patterns import DelayedPatternProvider

pattern_provider = DelayedPatternProvider(4)

import torch
test = torch.randn(1,24000*20)

test2 = {"wav" : torch.randn(2,1,24000*20),
        "original_lens" : torch.Tensor([[12000],[12000]]).int()}

codes = encodec(test)


In [3]:
from src.models.model import MuMRVQ
from src.models.Transformer.Encoder import VanillaEncoder
from src.models.Transformer.Decoder import VanillaDecoder
model = MuMRVQ(VanillaEncoder(layers=2), VanillaDecoder(layers=2) ,encodec, debug = False, pattern="none", mask_before=False)

/homes/jpmg86/anaconda3/envs/MuMRVQ/lib/python3.9/site-packages/torch/nn/modules/transformer.py:282: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  warnings.warn(f"enable_nested_tensor is True, but self.use_nested_tensor is False because {why_not_sparsity_fast_path}")


In [4]:
out_ = model(test2)

tensor(37, dtype=torch.int32)
tensor(37, dtype=torch.int32)
codes: torch.Size([2, 4, 1500])
padding_mask: torch.Size([2, 1501])
codes: torch.Size([2, 4, 1024])
padding_mask: torch.Size([2, 1024])
masking proba : 0.5
tokens to mask : 512
============== codes_masking ==============
tensor([[[0, 0, 1,  ..., 1, 0, 1],
         [0, 0, 1,  ..., 1, 0, 1],
         [0, 0, 1,  ..., 1, 0, 1],
         [0, 0, 1,  ..., 1, 0, 1]],

        [[1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0]]])
torch.Size([2, 4, 1024])
============== new x shape ================
torch.Size([2, 512, 960])
shape coming out of encoder: ============
torch.Size([2, 513, 960])
========= retained idx shape ============
torch.Size([2, 512])
=========== Masked without embeddings shape ========
torch.Size([2, 1024, 960])
========= all_masked.shape ==========
torch.Size([2, 1024, 960])
========= around masked index ========
tensor([[-0.3251, -0.2688

TypeError: forward() got an unexpected keyword argument 'padding_mask'

In [ ]:
out_['logits'][:,:,1:,:].shape

torch.Size([2, 1027, 3, 513])

In [ ]:
out_['codes'].shape

torch.Size([2, 4, 1024])

In [ ]:
from torch.nn import CrossEntropyLoss

CrossEntropyLoss(ignore_index=1026)(out_['logits'][:,:,:,1:],out_['codes'])

RuntimeError: size mismatch (got input: [2, 1027, 4, 512] , target: [2, 4, 1024]

In [ ]:
out_['codes']

tensor([[[1025,  732, 1025,  ..., 1025, 1026, 1026],
         [ 691,  691, 1025,  ..., 1025, 1026, 1025],
         [1025,  919, 1025,  ..., 1026, 1026, 1025],
         [1025, 1025,  988,  ..., 1026, 1026, 1026]],

        [[1025,  732, 1025,  ..., 1026, 1025, 1025],
         [ 691, 1008,  662,  ..., 1026, 1026, 1026],
         [1025, 1025,  186,  ..., 1026, 1025, 1026],
         [1025, 1025, 1025,  ..., 1025, 1026, 1026]]])

In [ ]:
test = torch.softmax(torch.Tensor([1,-float('inf')]),dim=0)